/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package people.dialogs;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Ophiran
 */
public class DialogErreur extends javax.swing.JFrame {

    /**
     * Creates new form DialogErreur
     */
    public DialogErreur() {
        this("Erreur de login !!!");
    }
    
    public DialogErreur(String Message) {
        initComponents();
        msg_Erreur_lab.setText(Message);
        ok_Button.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                MouseClickedOk(evt);
            }
        });
    }

    public void MouseClickedOk(MouseEvent evt){
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg_Erreur_lab = new javax.swing.JLabel();
        ok_Button = new javax.swing.JButton();
        Image_lab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_Erreur_lab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        ok_Button.setText("Ok");

        Image_lab.setIcon(new javax.swing.ImageIcon("C:\\Dropbox\\INPRES\\2em Annee\\JAVA\\Etape1\\ressources\\Images\\Error.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Image_lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok_Button)
                    .addComponent(msg_Erreur_lab))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msg_Erreur_lab)
                .addGap(54, 54, 54)
                .addComponent(ok_Button)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Image_lab)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_lab;
    private javax.swing.JLabel msg_Erreur_lab;
    private javax.swing.JButton ok_Button;
    // End of variables declaration//GEN-END:variables
}
